# Aumento de memória necessário para o remapping do Firebase
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties (Versão 26.2)
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.0.0
maven_group=com.nudgecraft

# Fabric API
fabric_api_version=0.157.0+26.2

# Firebase
firebase_version=9.2.0
